package_name: Trnasformer
save_file: "./test_dir"

ViT:
  patch_size: 4
  hidden_size: 48
  num_hidden_layers: 4
  num_attention_heads: 4
  intermediate_size: 192
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0
  initializer_range: 0.02
  image_size: 32
  num_classes: 10
  num_channels: 3
  qkv_bias: 1